# CircleCI doesn't automatically run builds on the beta branch (only master and PRs)
# so this is a github action to force it to do so.
name: Trigger beta release
on:
  push:
    branches: [beta]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release
        run: |
          curl \
            -X POST \
            --header "Content-Type: application/json" \
            -d '{"branch": "beta"}' \
            https://circleci.com/api/v1.1/project/github/artsy/eigen/build?circle-token=${{ secrets.CircleToken }}
